---
title: "A Webpage"
author: "Christina Bonsell"
date: "October 10, 2019"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F, message = F}
library(tidyverse)
library(cowplot)
library(scales)
library(DT)
library(leaflet)
library(sf)
library(ggmap)
```

```{r readfile}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method = "libcurl"), stringsAsFactors = F)
```


# Calculate Annual Escapement for Salmon Species
```{r, results="hide"}
annual_esc <- esc %>% 
  separate(sampleDate, c("Year","month","Day"), sep = "-", remove = F) %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(total_escapement = sum(DailyCount, na.rm=T)) %>% 
  filter(Species %in% c("Chinook","Sockeye","Chum", "Pink","Coho"))

head(annual_esc)
```

# Visulaize Escapement

Total Escapement by Region and Species

```{r, echo = F}
theme_set(theme_cowplot())


ggplot(annual_esc, aes(Species, total_escapement, fill=SASAP.Region))+
  geom_col(position=position_dodge())
```
Kodiak escapement over time by species

```{r echo = F}
my_theme <- theme_bw() +
  theme(legend.position = "bottom")

annual_esc %>%
  filter(SASAP.Region == "Kodiak") %>% 
  ggplot(aes(Year, total_escapement, color = Species))+
  geom_point()+
  geom_line()+
  scale_color_brewer(palette = "Dark2")+
  ylab("Escapement (no. fish)")+
  ggtitle("Kodiak Salmon Escapement")+
  my_theme


```

Escapement over time: all regions

```{r}
fig1 <- ggplot(annual_esc, aes(Year, total_escapement, color = Species))+
  geom_point()+
  geom_line()+
  facet_wrap(~SASAP.Region, scales = "free_y")

fig1

ggsave("escapement.png", fig1, width = 12, height = 7, units ="in")
```


# Map Sampling Locations

Create table with unique sampling locations, latitudes, and logitudes

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

```{r}
datatable(locations)
```

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addCircleMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~ Location) #can popup with data, combos etc

#email Sharon about EPA GIS files for Arctic projection

#can also use sf i/o leaflet which makes projections , but is static

#also don't have to use tiles!!! can just use shapefile
  
```

```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/north_polar_view_wms/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)


# 
# leaflet(locations) %>% 
#   addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/north_polar_view_wms/mapserv?",
#               layers = 'GEBCO_LATEST',
#               attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
#   addCircleMarkers(lng = ~Longitude,
#                    lat = ~Latitude,
#                    popup = ~ Location,
#                    radius = 5,
#                    # set fill properties
#                    fillColor = "salmon",
#                    fillOpacity = 1,
#                    # set stroke properties
#                    stroke = T,
#                    weight = 0.5,
#                    color = "white",
#                    opacity = 1)
```

```{r}
locations_sf <- locations %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)
locations_sf_3857 <- st_transform(locations_sf, 3857)

# Define a function to fix the bbox to be in EPSG:3857
# See https://github.com/dkahle/ggmap/issues/160#issuecomment-397055208
ggmap_bbox_to_3857 <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}

bbox <- c(-170, 68, -130, 74)   # This is roughly southern Alaska
ak_map <- get_stamenmap(bbox, zoom = 4)
ak_map_3857 <- ggmap_bbox_to_3857(ak_map)


ggmap(ak_map_3857) + 
  geom_sf(data = locations_sf_3857, inherit.aes = FALSE)
```

