---
title: "writing functions"
author: "Christina Bonsell"
date: "October 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(roxygen2)
```

# Create example data
```{r longway}
airtemps <- c(212, 30.3, 75, 32, -40)

airtemp1 <- (airtemps[1]-32)*5/9
airtemp2 <- (airtemps[2]-32)*5/9
airtemp3 <- (airtemps[3]-32)*5/9
airtemp4 <- (airtemps[4]-32)*5/9
```


# Write a function to convert from F to C

```{r FtoC}
#' Convert from Fahrenheit to Celsius
#'
#' A much more detalied explanation of how this function works,
#' @param fahr represents a numeric input in degrees Fahrenheit
#' @return the themp in Celsius
#' @export
#' example fahr_to_celsius(212)
fahr_to_celsius <- function(fahr){
  # check if fahr is numeric
  stopifnot(is.numeric(fahr))
  
  celsius <- (fahr-32)*5/9
  return(celsius)
}
```

# try out the function
```{r}
celsius <- fahr_to_celsius("airtemps")

celsius <- fahr_to_celsius(airtemps)

celsius
```


#a new function for C to F

```{r CtoF}
#' Convert from Celsius to Fahrenheit
#'
#' A much more detalied explanation of how this function works,
#' @param cel represents a numeric input in degrees Celsius
#' @return the themp in Fahrenheit
#' @export
#' example cel_to_fahr(100)
cel_to_fahr <- function(cel){
  # check if cel is numeric
  stopifnot(is.numeric(cel))
  
  fahr <- (cel*9/5)+32
  return(fahr)
}

cel_to_fahr(-30)

fahr <- cel_to_fahr(celsius)
fahr == airtemps
```

